    - name: Disable stub resolv
      replace:
              path: /etc/systemd/resolved.conf
              regexp: '#DNSStubListener=yes'
              replace: 'DNSStubListener=no'

    - name: Reload resolved
      service:
              name: systemd-resolved.service
              state: restarted

    - name: Update hosts file
      lineinfile:
              path: /etc/hosts
              line: "{{ HOSTIP }} {{ inventory_hostname }}"
              state: present

    - name: Resize ubuntu-lv volume to the max size
      lvol:
              vg: ubuntu-vg
              lv: ubuntu-lv
              size: +100%FREE
              resizefs: yes

    - name: Set node hostname
      ansible.builtin.hostname:
              name: "{{ inventory_hostname }}"

    - name: Install realm packages
      apt:
              name: 
               - realmd 
               - sssd 
               - sssd-tools 
               - libnss-sss 
               - libpam-sss 
               - adcli 
               - samba-common-bin 
               - oddjob 
               - oddjob-mkhomedir 
               - packagekit
               - nfs-common
               - pkg-config
               - libglvnd-dev
               - gcc
               - g++
               - default-jre
               - make
               - chrony
              state: present
              update_cache: yes
