---
###Play book installs the cuda driver, and toolkit to node
#### Join AD fro https://zerosandones.us/2023/01/06/join-linux-to-active-directory/
- name: Install and configure CUDA, and toolkit
  become: true
  gather_facts: true
  hosts: all
  vars:
          HOSTIP: "{{ ansible_default_ipv4.address }}"

  tasks:
          - name: Detect NVIDIA hardware
            shell: "lshw -C display|grep -c vendor: NVIDIA"
            register: nvidia_count
            ignore_errors: yes

  roles:
          #- initenv
          #- joinad
          - installnvidia 

