---
###Play book installs the cuda driver, and toolkit to node
#### Join AD fro https://zerosandones.us/2023/01/06/join-linux-to-active-directory/
- name: Install and configure CUDA, and toolkit
  become: true
  gather_facts: true
  hosts: all
  vars:
          HOSTIP: "{{ ansible_default_ipv4.address }}"
  tasks:

    - name: Disable stub resolv
      replace:
              path: /etc/systemd/resolved.conf
              regexp: '#DNSStubListener=yes'
              replace: 'DNSStubListener=no'

    - name: Reload resolved
      service:
              name: systemd-resolved.service
              state: restarted

    - name: Update hosts file
      lineinfile:
              path: /etc/hosts
              line: "{{ HOSTIP }} {{ inventory_hostname }}"
              state: present

    - name: Resize ubuntu-lv volume to the max size
      lvol:
              vg: ubuntu-vg
              lv: ubuntu-lv
              size: +100%FREE
              resizefs: yes

    - name: Set node hostname
      ansible.builtin.hostname:
              name: "{{ inventory_hostname }}"

    - name: Install realm packages
      apt:
              name: 
               - realmd 
               - sssd 
               - sssd-tools 
               - libnss-sss 
               - libpam-sss 
               - adcli 
               - samba-common-bin 
               - oddjob 
               - oddjob-mkhomedir 
               - packagekit
              state: present
              update_cache: yes

    - name: Check joined domain
      shell: realm list | wc -l
      register: joined_states
      ignore_errors: yes

    - name: Exit on error
      fail:
              msg: "Host {{ inventory_hostname }} is already a domain member"
      when: joined_states['stdout']|int > 0

    - name: Discover student.aast.edu domain
      command: realm discover {{ ADDOMAIN }}

      ##{{ ADDOMAIN }} --unattended --user={{ ADUSER }}%{{ ADPASS }}
    - name: Join student AD Domain
      shell: echo '{{ ADPASS }}' | realm join {{ ADDOMAIN }} -U {{ ADUSER }}
      register: join_result
      ignore_errors: no

    - name: Check the AD join result
      fail:
               msg: "Unable to join the AD domain, {{ join_result.stderr }}"
      when: join_result.rc != 0

    - name: Disable GPO
      lineinfile:
               path: /etc/sssd/sssd.conf
               line: "ad_gpo_access_control = permissive"
               insertafter: "[domain/{{ ADDOMAIN }}]"

    - name: Disable service line at sssd.conf
      replace:
              path: /etc/sssd/sssd.conf
              regexp: '^services ='
              replace: '#services ='

    - name: Restart SSSD service
      service:
               name: sssd
               state: restarted
               enabled: yes

    - name: Validate the AD join
      command: getent passwd {{ ADUSER }}@{{ ADDOMAIN }}
      register: validate_result
      ignore_errors: yes

    - name: Check the validation result
      fail:
              msg: "AD join validation failed, {{ validate_result.stderr }}"
      when: validate_result.rc != 0

    - name: Configure PAM.D session
      lineinfile:
              path: /etc/pam.d/common-session
              insertbefore: # end of pam-auth-update config
              line: session optional        pam_mkhomedir.so skel=/etc/skel umask=077

    - name: Restrict group login
      shell: realm deny --all && realm permit -g {{ ADGROUP }} && touch GroupRestriction
      args:
              creates: GroupRestriction

    - name: Install nfs-common
      apt:
              name: 
                  - nfs-common
              state: present



    - name: Add /home mount to /etc/fstab
      lineinfile:
              path: /etc/fstab
              line: "{{ NFSSERVER }}:{{ NFSHOMEPATH }} /home nfs defaults 0 0"
              state: present

    - name: Apply mounts
      shell: mount -a

    - name: End play
      meta: end_play

    - name: Block novueau 
      lineinfile:
        path: /etc/modprobe.d/blacklist-nouveau.conf
        line: options nouveau modeset=0
        state: present
        create: true

    - name: Update init ramfs
      shell: update-initramfs -u

    - name: Reboot the server
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0

    - name: Wait for the host to boot
      wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        delay: 60
        timeout: 120
      connection: local

    - name: Install needed packages
      apt:
        name:
          - pkg-config
          - libglvnd-dev
          - gcc 
          - g++
          - default-jre 
          - make
        state: present
        update_cache: yes

    - name: Copy driver, and toolkit
      copy:
        src: files/{{ item }}
        dest: /home/administrator
        mode: 0555
      loop:
        - "{{ DRIVERNAME }}"
        - "{{ TOOLKITNAME }}"

    - name: Install nvidia driver
      shell: "/home/administrator/{{ DRIVERNAME }} -s"

    - name: Install nvidia toolkit
      shell: "/home/administrator/{{ TOOLKITNAME }} --toolkit --samples --silent"

    - name: Adding path
      lineinfile:
        path: /etc/profile
        line: "PATH=${PATH}:/{{ CUDADIR }}"
        state: present
