    - name: Detect NVIDIA hardware
      shell: "lshw -C display|grep -c vendor: NVIDIA"
      register: nvidia_count
      ignore_errors: yes

    - name: End if no nvidia GPU installed
      meta: end_play
      when: nvidia_count['stdout']|int == 0

    - name: Block novueau 
      lineinfile:
        path: /etc/modprobe.d/blacklist-nouveau.conf
        line: options nouveau modeset=0
        state: present
        create: true

    - name: Update init ramfs
      shell: update-initramfs -u

    - name: Reboot the server
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0

    - name: Wait for the host to boot
      wait_for:
        port: 22
        host: "{{ inventory_hostname }}"
        delay: 60
        timeout: 120
      connection: local

    - name: Copy driver, and toolkit
      copy:
        src: files/{{ item }}
        dest: /home/administrator
        mode: 0555
      loop:
        - "{{ DRIVERNAME }}"
        - "{{ TOOLKITNAME }}"

    - name: Install nvidia driver
      shell: "/home/administrator/{{ DRIVERNAME }} -s"

    - name: Install nvidia toolkit
      shell: "/home/administrator/{{ TOOLKITNAME }} --toolkit --samples --silent"

    - name: Adding path
      lineinfile:
        path: /etc/profile
        line: "PATH=${PATH}:/{{ CUDADIR }}"
        state: present
